executors:
  my-executor:
    docker:
      - image: 'golang:1.14.3-alpine'

orbs:
  gcp-gcr: circleci/gcp-gcr@0.11.0
version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/Monty-Python/tech-fest
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...

      - setup_remote_docker:
          version: 19.03.13

      # build the application image
      - run: docker build -t tech-fest/app:$CIRCLE_BUILD_NUM .

      # docker hub login
      # - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWD

      # push image
      # - run: docker push tech-fest/app:$CIRCLE_BRANCH

      